# Generated by Django 6.0.6 on 2026-06-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_fantasylineup_fantasytransfer_fantasylineupplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasylineup',
            name='final_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Pontuação final'),
        ),
        migrations.AddField(
            model_name='fantasylineup',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizada em'),
        ),
    ]
