# Generated by Django 6.0.6 on 2026-06-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_fantasylineup_coach'),
        ('scores', '0003_fantasylineup_final_points_and_more'),
    ]

    operations = [
    ]
