# Generated by Django 6.0.6 on 2026-06-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_alter_competition_options_alter_fixture_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Fase atual'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('competition',), name='unique_current_stage_per_competition'),
        ),
    ]
