# Generated by Django 6.0.6 on 2026-06-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatistic',
            name='goals_conceded',
            field=models.IntegerField(default=0, verbose_name='Gols Sofridos'),
        ),
    ]
