# Generated by Django 6.0.6 on 2026-06-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_stage_is_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim previsto'),
        ),
        migrations.AddField(
            model_name='stage',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizada em'),
        ),
        migrations.AddField(
            model_name='stage',
            name='lineup_deadline_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo para escalação'),
        ),
        migrations.AddField(
            model_name='stage',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início'),
        ),
    ]
