# Generated by Django 6.0.6 on 2026-06-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_playerstatistic_goals_conceded'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatistic',
            name='saves',
            field=models.IntegerField(default=0, verbose_name='Defesas'),
        ),
    ]
