# Generated by Django 6.0.6 on 2026-06-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_stage_ends_at_stage_finished_at_and_more'),
        ('football', '0005_playerstatistic_saves'),
    ]

    operations = [
    ]
